//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public string Admin_id { get; set; }
        public string Admin_UserName { get; set; }
        public string Admin_Password { get; set; }
        public string Admin_FN { get; set; }
        public string Admin_LN { get; set; }
        public string Admin_sex { get; set; }
        public string Admin_Email { get; set; }
        public int Admin_Phone { get; set; }
    }
}
