//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string Order_id { get; set; }
        public string Product_id { get; set; }
        public string User_id { get; set; }
        public string User_Address { get; set; }
        public Nullable<double> SumPrice { get; set; }
        public byte[] Order_date { get; set; }
    }
}
