//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Product_id { get; set; }
        public string Product_name { get; set; }
        public byte[] Product_image { get; set; }
        public string Product_desciption { get; set; }
        public string Product_color { get; set; }
        public string Product_type { get; set; }
        public double Product_price { get; set; }
        public int Product_amount { get; set; }
    }
}
