//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public string Store_id { get; set; }
        public string Store_name { get; set; }
        public string Emp_username { get; set; }
        public string Emp_password { get; set; }
        public string Emp_FN { get; set; }
        public string Emp_LN { get; set; }
        public string Emp_sex { get; set; }
        public string Emp_address { get; set; }
        public string Emp_Email { get; set; }
        public int Emp_Phone { get; set; }
    }
}
