//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string User_id { get; set; }
        public string UserName { get; set; }
        public string User_password { get; set; }
        public string User_FN { get; set; }
        public string User_LN { get; set; }
        public System.DateTime User_Birth { get; set; }
        public string User_sex { get; set; }
        public string User_address { get; set; }
        public string User_Email { get; set; }
        public int User_Phone { get; set; }
    }
}
